

corpos_text = {
    
    '0_9_9':
    ["In my opinion, making more money doesn’t always mean you’ll be happier at work. I think that job satisfaction is more important and has more meaning than pursuing a job that has a high salary. I think the reason for happiness and satisfaction is not how much money you make but it’s whether you really want to do the job. I think people can turn a hobby into their own job. If you can’t do it now just keep looking for it. Search until you find a job that is really suitable for you. Then when thinking about the future it’s really important to be happy in your personal life, and that should never be based on the amount of money or quantity of money that you will receive. Because if you are happy and satisfied with your job, then you will be satisfied when you look at other things around you. After all, salary comes once a month, but job satisfaction is your whole career every minute of your day."],

    '0_10_10':
    ["I would prefer to choose a major that is easy to find a good job in the future like finance or marketing for example. There’s no one that can deny the most common reason for attending university is to get prepared for a good job in the future. So whether the major will lead us to a good job or not is the most important reason why we choose our major. If we find a good job with a decent payment, we can use the money that we have earned from it to satisfy our own interests. For example, I like painting a lot. However I chose painting as my profession. I don't think I can make a lot of money as a painter. But if I go for a major like finance I can get a finance related job after graduation. After university I can get a high salary and in my free time I can use my salary to hire a professional teacher to teach me how to draw."],

    '0_11_11':
    ["I’ve got a room in my house that is my study room. I have a lot of books in my study room, such as fashion magazines, inspirational books, etc. Also there is a computer in my study room. Usually I will check my computer to learn some study related information such as math problems that I just can’t do. I also am able to use it for fun. For example I am able to catch up on the latest Netflix episodes of my favorite show, and sometimes I’m able to use it to check out some clothes and look inside the latest fashion magazines. However, most of the time I just add them to my cart and don’t  actually buy them. Because I don’t have a job at this time as I was a student I didn’t have much money to buy them. In my spare time I usually like to surf the Internet and pay close attention to the newest fashion news or find some valuable books to recharge the energy inside myself. These books can make me healthier and energetic."],

    '0_13_13':
    ["Many of my favorite places in my city have already been destroyed. A few of those favorite places in mind we’re basically a few kilometers from my home. They had no name but these are spots like a small pond with bamboo trees and birds chirping. I always used to bother my father to take me there for its beauty. Presently my favorite place happens to be Hadano Tokawa park. I am in love with the bodies of water in this place and it’s beautiful. We often go up the mountain along long stone steps and I enjoy the scenery along the way. The valley is full of trees and a long drive through it is so much fun. I feel very happy when I’m close to nature. As I feel grateful for the opportunity to be next to nature. I believe nature is amazing and full of magic. When the cherry blossoms are in full bloom we can have a barbecue at the foot of the mountain. However, I like this place when it’s not a weekend as it is already too crowded with people these days."],

    '0_14_14':
    ["My favorite sport is yoga. I think it’s completely changed the way I look at sports. Yoga is not for competing or being the best, and it’s not about how you look. It’s all about how you feel. Understanding that connection with your own body and discovering the fun in each and every movement is exciting. Every day is different as you discover more and more about your body's abilities and it’s limitations. I find that it grounds me and calms me down some days, and fills me up with energy on other days. Another reason I like yoga is because I usually have a quiet personality in my life so it doesn’t take a lot of time for me to get used to it. Just staying in a quiet place and exercising makes me feel comfortable. It also makes me more aware of my body movements and helps me to get good balance. Additionally, I also like to meditate in yoga, it makes me feel free and relaxes me a lot. If you want to try something new I would highly recommend trying out yoga. I’ll keep doing yoga about three days a week now and it puts me in a good mood every time."],

    '0_15_15':
    ["Well, I think it’s quite common to see people moving from place to place for different reasons. I also experienced the same thing when I was in the third grade primary school. Actually my parents and I used to live in a village in a joint family house with my grandparents. The experience of being together was so amazing, and the peaceful life from the village away from cities cannot be fully explained in words. However, my family decided to move to Japan because my grandfather was actually Japanese. It was not easy for us to leave our hometown to live in a city where nobody knew us. We found it hard to adapt to a new place and environment. Luckily, our neighbor is really a friendly and kind hearted person. He helped us in every possible way to make us feel comfortable and make the transition to Japan convenient. Although we missed our family and village house a lot, we slowly and steadily used to see life, especially visiting shopping malls, cafés, parks, playgrounds, studying in libraries, and other conveniences of living in a city. I feel that although anyone will feel a little uncomfortable when they go an hour from your place, the variety of change will increase that person’s experience in life."],

    '0_16_16':
    ["My last trip was when I was about to graduate from my university. At the time, I went to Okinawa alone and it was my first time traveling alone. Since it was my first time traveling alone I had no information about the area and no idea how to read a map. I didn't know my left or my right Iet alone my north and south. I just bought a suitcase and booked a hotel in Okinawa with no plans. I remember that night when I arrived at my hotel I checked my phone to see some of the famous spots in Okinawa. The next day I had breakfast at the hotel and left with my bag on my back. I remember that my first day I went to the famous aquarium but I can’t remember the name of it right now. I touched a beautiful starfish, watched a dolphin show and took many pictures of plants on the seashore. My second day was to go to the famous temple in Okinawa although I have also forgotten it’s name now too. I made a wish for an easy to find job and put my lucky fortune in a tree in the temple. I hope my future goes well and fortune will bring me a good future."],

    '0_65_65':
    ["The best time of the year for me is when I get to volunteer at the Buddhist temple. It includes leading the way for serving as a guide for people who come to the Buddhist temple. Last week I also went to the Buddhist temple and was assigned to the job of standing in front of the elevator to be a guide. When people passed by, I would greet them with a smile and a bow. I remember a very old man who didn’t know where the place of worship was. I helped him and walked with him to that place. He happily chatted with me and said that it was his first time to come into the Buddhist temple in Yokohama. He told me it was because he lives in Chigasaki, where he only goes to temples in Shonan. I am very happy to help others through the Buddhist temple and I have received many unexpected surprises."],

    '0_66_66':
    ["To me, the best time of the year falls after winter vacations. During this period of time there is a lot of work to do because of our entire course, and then we sit in our homes studying. But still, I like this time because we are free from school and waking up early in the morning. And then the week begins to break down. The last day of school is the most memorable day of school in the whole of the year. Then the day arrives that every student fancies…. THE SUMMER BREAK!!! And that is why we get to sleep more. All of the students enjoy themselves with their families and best friends. People visit different places in their own beloved country. Student’s hang out at different eating places; where they eat less and laugh a lot. Girls talk about different fashion icons, and brands-gossip is their most akin topic. Boys like to talk about sports and superb cars."],

    '0_73_73':
    ["Well, emotion is one of the basic things that make us human. And anger is one of them. I normally get angry when a speedy rash driving vehicle crosses me on-road or someone with a high pitch modified exhaust system. They do it just for fun, not considering how they affect others. For a few seconds, I am really tempered, and would like to say: ‘it’s so terrible! I’m so damn sick of these cars! Nobody can tolerate them! Nobody drives like this, you should really listen to yourselves to hear how loud your car is!' I think getting angry is human nature and hard to control. For me, another example is when someone tells rumors about me, or backstabbing me will actually make me angry."],

    '0_74_74':
    ["I think the thing that makes me angry is when someone is repeatedly late and always not on time. Being repeatedly late is a sign of disrespect. It’s easy to make people feel angry and I think most people understand that being late is a sign of not respecting another person‘s time. It’s OK to get angry at people who are always late. And sometimes I know that I can’t change other people's behaviors, but what I can change is how I react to it. Sometimes you need to have a discussion with people saying, “If you're always going to be late, I don’t want to make plans with you anymore.” This sets a clear boundary and states that you need to be treated fairly. A good friend will understand and try to change. A selfish friend will agree and still be late anyway. However a codependent friend will attack you with unreasonable demands."],

    '0_81_81':
    ["Today I went to collect rent from our apartment. Usually, they come to our house to pay bills but they had delayed more than two months. Someone has not paid her electric bills for the last two months so I asked her about it. She said that her son's exams were going on and that's why she needs money to spend on him. She and her husband are working hard to keep the roof above their head. I was impressed. So I told her not to worry about bills. And asked her if she needs any other help. She said she was worried about her son. Poor guy was very stressed. He was working really hard to get into a reputed engineering college. She was really depressed because last year, due to bad rank her elder son couldn't make it into a good college and they did not have much money to support him. Reservation killed her dreams and all hope for a bright future."],

    '0_82_82':
    ["The last time I got lost in another city was in 2017. I went to Singapore with two of my friends for our summer vacation. Singapore has a very complex road network. And someone without a sense of direction like us will easily get lost even if you’re using a map or following the instructions of the GPS. Besides, Singapore is a historic city with a large number of tourist attractions. Some attractions are quite near each other, so we didn’t have to take the bus, we just walked to the next attraction. We regretted the decision not to take the bus since we couldn’t find the right way. On our way to the next attraction we chatted with each other for a long time and the worst thing was that the signal on our cellphones were not very good and we could not connect to the map. We were so worried and did not know what to do. There were hardly any people on a quiet street. We had to keep on walking and I hope that we could meet someone new."],

    '0_87_87':
    ["The thing I don’t like is internet harassment. These days computers are part of our lives. People are free to do everything on the Internet. They can say or do whatever they feel there. However, the Internet also allows for people to have a platform to harass people. They are able to give bad or rude comments to other people. This is also the case for celebrities, who are being attacked by Internet commenters all the time. A famous female star from Korea committed suicide because of this harassment. The government took some actions to control the networks and users must be registered with their real names. It worked and this form of harassment has been controlled in some way. We need to behave ourselves even without the supervision of law. I hope you all protect yourselves. And when you send messages to people, be careful about what you write and post online. I don’t share an unkind personal comment or image. Remember that just because you have a computer in front of you, it doesn’t mean that the person on the other side is not a real human being."],

    '0_88_88':
    ["""I look down on people who cry in public a lot. When someone gets a bad grade on a test and starts to sob, it pisses me off. It seems very manipulative because it is almost pressuring the people around you to comfort you when nothing that bad actually happened. To me, it is the same as when someone says "I am sooooo ugly/dumb/etc." and then waits for the people around them to go "nooo, you are the smartest, prettiest, coolest person I have ever met." It is like they are turning the people around them into their safety blanket. Also I look down on people when they constantly blame others for the bad things happening to them but do not bother to think of solutions. I have a friend who keeps complaining about how he owes $700 to his phone provider, $1500 in credit card debt, etc, but all he does is spend his money on cigarettes, liquor and other drugs. I suggest paying everything off little by little and putting some money aside to build a savings, but he ignores it and the debt just keeps piling up."""],

    '0_95_95':
    ["Well the world is so small. Actually, last year, I was visiting a client during my work time. On the way back, I ran into a college classmate who was walking on the street. We were both very surprised to see one another, ‘wow, Why are you here too? Long time no see!’ ‘It's been three or four years since we've seen each other, right?’ We are very happy to meet together after not seeing each other for such a long time. We gave each other a warm hug and decided to spend some time together. We went to a cafe to sit. While we were eating and drinking, He told me that he is now working at a middle school as an English teacher. ‘Oh, you found your dream job! I remember you wanted to be an English teacher when you were in college!’ Overall, it was the time when I unexpectedly and surprisingly met my friend!"],

    '0_96_96':
    ["One of my friends asked for my mother’s phone number as he wanted to clarify about the reopening of his college. He joined the same institute where my mother is working currently. I just lent my mother’s phone number to him. A day before my departure, someone rang the bell at 6:30 pm and I just went down to open the door. When I opened the door, I was shocked to see my friends. It was a plan which they had made for me under a lot of chaos with my mother, ‘oh! How did you find my apartment? How did you know I was leaving today!?” ”I asked your mom’s number for this!” “You didn’t show up, that surely is a surprise for me!!” I never expected this from them, I was completely speechless."],

    '0_103_103':
    ["When I was in university, almost more than 10 years ago, the community security was not very good and we are often more than not in dangerous situations. One time, I was walking home from work, waiting at the bus stop for a bus. Then I heard the sound of gunfire from across the road. Police cars came around and the police shot at people across the street. I was so scared! The main reason was because you have no place to hide. You’re at a bus station and there's no place to go. There was another time when I was in Los Angeles driving and I took the wrong road and went on a small local road. And I’m not exaggerating here but both sides of the road were full of homeless people. Those people were moving around on the road and I was very nervous. They ignored the traffic rules and came right up to the car and made me stop my car. They shook the car and swore at me.  I thought to myself this is horrible because a few days ago someone was shot dead and maybe I’ll be next."],

    '0_104_104':
    ["One thing that scared me was once when I was out driving at night trying to get gas. Well maybe it was a little bit after 12 o’clock. I went to the gas station to fill up. I was finishing up and was checking out with my money, and then a woman suddenly jumped out from the side of my car, with blood on her face.  and I was like, “What’s going on here?” Then she said “I’ve been in a traffic accident! Can you give me some money? I want to go home.” and I only had $20 on me. So I gave her $20. I said “That’s all I have.” She said, “$20 dollars is not enough.” I told her that I couldn’t help her. I only have $20. She told me, “Well you can use your credit card, you can go over there and get the money.” Because we were at a gas station. She told me to go inside the gas station and use my credit card to get money. I told her “ Forget that, I can only help you here, $20 will do.” Then when I looked closely at her face I noticed she was quite young, like a University student. Maybe she came here on purpose to ask for money."],

    '0_111_111':
    ["Some people pelting stones at dogs and watching them yelp in pain amused, Some little children begging on the streets, people driving with mobiles glued to their ears, women standing in metros while the male passengers nicely remain stuck to their seats or mobile, talking loudly on the mobile often causing irritation to fellow passengers, all these make me disgust. Another example is in the hospital. There were almost 34 patients waiting before me. People of different ages are here. One thing that disgusted me here is that people are using mobile phones to watch YouTube videos and other videos in high volume. They have almost forgotten why they are here. They broke the peace around the hospital. Now mobile phones have become very close to everyone and some people can't live without using them. I appreciate the technology but we should obey some basic etiquettes."],

    '0_112_112':
    ["I think I dislike places that are crowded and people act like they’re crazy. It could be a club, a railway station,or a place where people are going insane. Situations like this make me feel uncomfortable especially when the place is too noisy or if I have been in an environment that is noisy for a long time. I don’t like the feeling of being pressed against people. Also I am not used to being in a situation where there is a lot of loud noises all the time. I remember I was at a private party that was very loud and it made me feel a little tired and sleepy. So if I feel a little bit uncomfortable, I usually drop my plans if I know the place will be crawling with thousands of people. Also, I don’t like places where the sunshine is too hot or the weather is extremely cold. Extreme cold and extreme heat will make me a bit uncomfortable."]

}